using System;
using System.ComponentModel;
using System.Globalization;

namespace LlamaServerLauncher.Resources;

public class LocalizedStrings : INotifyPropertyChanged
{
    private static readonly System.Resources.ResourceManager _resourceManager = new("LlamaServerLauncher.Resources.Strings", typeof(LocalizedStrings).Assembly);
    private static CultureInfo _currentCulture = CultureInfo.InvariantCulture;
    
    public static event Action? CultureChanged;
    
    public event PropertyChangedEventHandler? PropertyChanged;

    public string this[string key] => GetString(key);

    public static string GetString(string key)
    {
        return _resourceManager.GetString(key, _currentCulture) ?? key;
    }

    public static void SetCulture(CultureInfo culture)
    {
        _currentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        CultureInfo.CurrentCulture = culture;
        Instance.OnPropertyChanged(string.Empty);
        CultureChanged?.Invoke();
    }

    public static CultureInfo CurrentCulture => _currentCulture;

    public static LocalizedStrings Instance { get; } = new();

    protected void OnPropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    public string WindowTitle => GetString("WindowTitle");
    public string ServerControl => GetString("ServerControl");
    public string StartServer => GetString("StartServer");
    public string TrayNoServersRunning => GetString("TrayNoServersRunning");
    public string StopServer => GetString("StopServer");
    public string RestartServer => GetString("RestartServer");
    public string UnloadModel => GetString("UnloadModel");
    public string UnloadAllModels => GetString("UnloadAllModels");
    public string NoLoadedModels => GetString("NoLoadedModels");
    public string Show => GetString("Show");
    public string Close => GetString("Close");
    public string AutoRestartOnCrash => GetString("AutoRestartOnCrash");
    public string StatusStopped => GetString("StatusStopped");
    public string WindowTitleRunning => GetString("WindowTitleRunning");
    public string TabProfiles => GetString("TabProfiles");
    public string TabMain => GetString("TabMain");
    public string TabCustom => GetString("TabCustom");
    public string TabGeneration => GetString("TabGeneration");
    public string TabOptions => GetString("TabOptions");
    public string TabSettings => GetString("TabSettings");
    public string Profile => GetString("Profile");
    public string Save => GetString("Save");
    public string Load => GetString("Load");
    public string Delete => GetString("Delete");
    public string Rename => GetString("Rename");
    public string Clear => GetString("Clear");
    public string Export => GetString("Export");
    public string ExportDialogTitle => GetString("ExportDialogTitle");
    public string ExportFormatJson => GetString("ExportFormatJson");
    public string ExportFormatBat => GetString("ExportFormatBat");
    public string ExportToBat => GetString("ExportToBat");
    public string Import => GetString("Import");
    public string Paths => GetString("Paths");
    public string LlamaServerExe => GetString("LlamaServerExe");
    public string ModelM => GetString("ModelM");
    public string ModelsDir => GetString("ModelsDir");
    public string Browse => GetString("Browse");
    public string NetworkSettings => GetString("NetworkSettings");
    public string Host => GetString("Host");
    public string Port => GetString("Port");
    public string ModelParameters => GetString("ModelParameters");
    public string ContextSize => GetString("ContextSize");
    public string Threads => GetString("Threads");
    public string GpuLayers => GetString("GpuLayers");
    public string CpuMoe => GetString("CpuMoe");
    public string GenerationParameters => GetString("GenerationParameters");
    public string Temperature => GetString("Temperature");
    public string MaxTokens => GetString("MaxTokens");
    public string BatchSize => GetString("BatchSize");
    public string UBatchSize => GetString("UBatchSize");
    public string MinP => GetString("MinP");
    public string MMProj => GetString("MMProj");
    public string CacheTypeK => GetString("CacheTypeK");
    public string CacheTypeV => GetString("CacheTypeV");
    public string TopK => GetString("TopK");
    public string TopP => GetString("TopP");
    public string RepeatPenalty => GetString("RepeatPenalty");
    public string AdditionalOptions => GetString("AdditionalOptions");
    public string FlashAttention => GetString("FlashAttention");
    public string WebUI => GetString("WebUI");
    public string Embedding => GetString("Embedding");
    public string Slots => GetString("Slots");
    public string Metrics => GetString("Metrics");
    public string ApiKey => GetString("ApiKey");
    public string Alias => GetString("Alias");
    public string LogFile => GetString("LogFile");
    public string VerboseLogging => GetString("VerboseLogging");
    public string CustomArguments => GetString("CustomArguments");
    public string CustomArgumentToggleHint => GetString("CustomArgumentToggleHint");
    public string ServerLog => GetString("ServerLog");
    public string ClearLog => GetString("ClearLog");
    public string CopyLog => GetString("CopyLog");
    public string SaveLog => GetString("SaveLog");
    public string SaveLogDialogTitle => GetString("SaveLogDialogTitle");
    public string TooltipCopyLog => GetString("TooltipCopyLog");
    public string TooltipSaveLog => GetString("TooltipSaveLog");
    public string TooltipToggleLogMaximize => GetString("TooltipToggleLogMaximize");
    public string AutoScrollLog => GetString("AutoScrollLog");
    public string Language => GetString("Language");
public string English => GetString("English");
    public string Russian => GetString("Russian");

    public string ErrorTitle => GetString("ErrorTitle");
    public string WarningTitle => GetString("WarningTitle");
    public string ConfirmTitle => GetString("ConfirmTitle");
    public string OK => GetString("OK");
    public string Cancel => GetString("Cancel");
    public string Yes => GetString("Yes");
    public string No => GetString("No");
    public string FailedToStartServer => GetString("FailedToStartServer");
    public string PleaseEnterProfileName => GetString("PleaseEnterProfileName");
    public string UnsavedChangesTitle => GetString("UnsavedChangesTitle");
    public string UnsavedChangesMessage => GetString("UnsavedChangesMessage");
    public string UnsavedChangesWarning => GetString("UnsavedChangesWarning");
    public string AutoRestarting => GetString("AutoRestarting");
    public string FailedToAutoRestart => GetString("FailedToAutoRestart");
    public string ConfirmCloseTitle => GetString("ConfirmCloseTitle");
    public string ConfirmCloseMessage => GetString("ConfirmCloseMessage");
    public string DropBatFile => GetString("DropBatFile");
    public string TooltipClearAllFields => GetString("TooltipClearAllFields");
    public string EnterNewProfileName => GetString("EnterNewProfileName");
    public string RenameProfileFailed => GetString("RenameProfileFailed");
    public string ConfirmDelete => GetString("ConfirmDelete");
    public string ErrorLoadingFile => GetString("ErrorLoadingFile");
    public string ExportAll => GetString("ExportAll");
    public string ImportAll => GetString("ImportAll");
    public string ExportAllDialogTitle => GetString("ExportAllDialogTitle");
    public string ImportAllDialogTitle => GetString("ImportAllDialogTitle");
    public string ExportAllSuccess => GetString("ExportAllSuccess");
    public string ImportAllSuccess => GetString("ImportAllSuccess");
    public string ExportAllFailed => GetString("ExportAllFailed");
    public string ImportAllFailed => GetString("ImportAllFailed");
    public string ExportAllFilter => GetString("ExportAllFilter");
    public string ImportAllFilter => GetString("ImportAllFilter");
    public string NoProfilesToExport => GetString("NoProfilesToExport");
    public string TooltipExportAll => GetString("TooltipExportAll");
    public string TooltipImportAll => GetString("TooltipImportAll");

    public string EnableLog => GetString("EnableLog");
    public string ShowLog => GetString("ShowLog");
    public string HideLog => GetString("HideLog");
    public string ShowTabPanel => GetString("ShowTabPanel");
    public string HideTabPanel => GetString("HideTabPanel");

    public string TooltipModelPath => GetString("TooltipModelPath");
    public string TooltipModelsDir => GetString("TooltipModelsDir");
    public string TooltipHost => GetString("TooltipHost");
    public string TooltipPort => GetString("TooltipPort");
    public string TooltipContextSize => GetString("TooltipContextSize");
    public string TooltipThreads => GetString("TooltipThreads");
    public string TooltipGpuLayers => GetString("TooltipGpuLayers");
    public string TooltipCpuMoe => GetString("TooltipCpuMoe");
    public string TooltipTemperature => GetString("TooltipTemperature");
    public string TooltipMaxTokens => GetString("TooltipMaxTokens");
    public string TooltipBatchSize => GetString("TooltipBatchSize");
    public string TooltipUBatchSize => GetString("TooltipUBatchSize");
    public string TooltipMinP => GetString("TooltipMinP");
    public string TooltipMMProj => GetString("TooltipMMProj");
    public string TooltipCacheTypeK => GetString("TooltipCacheTypeK");
    public string TooltipCacheTypeV => GetString("TooltipCacheTypeV");
    public string TooltipTopK => GetString("TooltipTopK");
    public string TooltipTopP => GetString("TooltipTopP");
    public string TooltipRepeatPenalty => GetString("TooltipRepeatPenalty");
    public string TooltipFlashAttention => GetString("TooltipFlashAttention");
    public string TooltipWebUI => GetString("TooltipWebUI");
    public string TooltipEmbedding => GetString("TooltipEmbedding");
    public string TooltipSlots => GetString("TooltipSlots");
    public string TooltipMetrics => GetString("TooltipMetrics");
    public string TooltipApiKey => GetString("TooltipApiKey");
    public string TooltipAlias => GetString("TooltipAlias");
    public string TooltipLogFile => GetString("TooltipLogFile");
    public string TooltipCustomArguments => GetString("TooltipCustomArguments");

    public string TooltipFontSize => GetString("TooltipFontSize");
    public string TooltipCurrentCommand => GetString("TooltipCurrentCommand");
    public string CommandPreview => GetString("CommandPreview");
    public string ToastCorruptFileSkipped => GetString("ToastCorruptFileSkipped");
    public string ToastCustomDataPathMissing => GetString("ToastCustomDataPathMissing");
    public string ConfirmDeleteCorruptFile => GetString("ConfirmDeleteCorruptFile");
    public string ToastCorruptFileDeleted => GetString("ToastCorruptFileDeleted");
    public string ToastCorruptFileDeleteFailed => GetString("ToastCorruptFileDeleteFailed");

    public string Appearance => GetString("Appearance");
    public string ThemeVariant => GetString("ThemeVariant");
    public string TooltipThemeVariant => GetString("TooltipThemeVariant");
    public string ColorScheme => GetString("ColorScheme");
    public string TooltipColorScheme => GetString("TooltipColorScheme");
    public string FontFamily => GetString("FontFamily");
    public string TooltipFontFamily => GetString("TooltipFontFamily");

    public string ColorSchemeDefault => GetString("ColorSchemeDefault");
    public string ColorSchemeOcean => GetString("ColorSchemeOcean");
    public string ColorSchemeForest => GetString("ColorSchemeForest");
    public string ColorSchemeSunset => GetString("ColorSchemeSunset");
    public string ColorSchemeUbuntu => GetString("ColorSchemeUbuntu");
    public string ColorSchemeCustom => GetString("ColorSchemeCustom");
    public string CustomColorsHeader => GetString("CustomColorsHeader");
    public string CustomColorWindow => GetString("CustomColorWindow");
    public string CustomColorPanel => GetString("CustomColorPanel");
    public string CustomColorCommand => GetString("CustomColorCommand");
    public string CustomColorAccent => GetString("CustomColorAccent");
    public string CustomColorSeparator => GetString("CustomColorSeparator");
    public string ResetCustomColors => GetString("ResetCustomColors");

    public string AutoFitHeight => GetString("AutoFitHeight");

    public string DownloadLlama => GetString("DownloadLlama");
    public string UpdateLlama => GetString("UpdateLlama");
    public string ExecutablePathPlaceholder => GetString("ExecutablePathPlaceholder");
    public string DownloadDialogTitle => GetString("DownloadDialogTitle");
    public string DownloadToFolder => GetString("DownloadToFolder");
    public string SelectDownloadFolder => GetString("SelectDownloadFolder");
    public string SelectRelease => GetString("SelectRelease");
    public string SelectBuild => GetString("SelectBuild");
    public string DownloadButton => GetString("DownloadButton");
    public string LoadingReleases => GetString("LoadingReleases");
    public string ReleaseNotFound => GetString("ReleaseNotFound");
    public string NoAssetsForOS => GetString("NoAssetsForOS");
    public string Downloading => GetString("Downloading");
    public string Extracting => GetString("Extracting");
    public string DownloadComplete => GetString("DownloadComplete");
    public string DownloadFailed => GetString("DownloadFailed");
    public string PromptDownloadLlama => GetString("PromptDownloadLlama");
    public string AddToPathPrompt => GetString("AddToPathPrompt");
    public string ChangeVersionLlama => GetString("ChangeVersionLlama");
    public string OpenInBrowser => GetString("OpenInBrowser");
    public string TooltipOpenInBrowser => GetString("TooltipOpenInBrowser");

    public string PlaceholderModelPath => GetString("PlaceholderModelPath");
    public string PlaceholderModelsDir => GetString("PlaceholderModelsDir");
    public string PlaceholderHost => GetString("PlaceholderHost");
    public string PlaceholderPort => GetString("PlaceholderPort");
    public string PlaceholderContextSize => GetString("PlaceholderContextSize");
    public string PlaceholderThreads => GetString("PlaceholderThreads");
    public string PlaceholderGpuLayers => GetString("PlaceholderGpuLayers");
    public string PlaceholderCpuMoe => GetString("PlaceholderCpuMoe");
    public string PlaceholderTemperature => GetString("PlaceholderTemperature");
    public string PlaceholderMaxTokens => GetString("PlaceholderMaxTokens");
    public string PlaceholderBatchSize => GetString("PlaceholderBatchSize");
    public string PlaceholderUBatchSize => GetString("PlaceholderUBatchSize");
    public string PlaceholderMinP => GetString("PlaceholderMinP");
    public string PlaceholderTopK => GetString("PlaceholderTopK");
    public string PlaceholderTopP => GetString("PlaceholderTopP");
    public string PlaceholderRepeatPenalty => GetString("PlaceholderRepeatPenalty");
    public string PlaceholderApiKey => GetString("PlaceholderApiKey");
    public string PlaceholderAlias => GetString("PlaceholderAlias");
    public string PlaceholderLogFilePath => GetString("PlaceholderLogFilePath");
    public string PlaceholderMmprojPath => GetString("PlaceholderMmprojPath");
    public string PlaceholderCustomArguments => GetString("PlaceholderCustomArguments");
    public string PortValidationWarning => GetString("PortValidationWarning");
    public string HostValidationWarning => GetString("HostValidationWarning");

    public string ParallelSlots => GetString("ParallelSlots");
    public string ContBatching => GetString("ContBatching");
    public string Timeout => GetString("Timeout");
    public string CachePrompt => GetString("CachePrompt");
    public string Mlock => GetString("Mlock");
    public string Mmap => GetString("Mmap");
    public string Reasoning => GetString("Reasoning");
    public string ReasoningBudget => GetString("ReasoningBudget");
    public string Seed => GetString("Seed");
    public string PresencePenalty => GetString("PresencePenalty");
    public string FrequencyPenalty => GetString("FrequencyPenalty");
    public string ContextShift => GetString("ContextShift");

    public string TooltipParallelSlots => GetString("TooltipParallelSlots");
    public string TooltipContBatching => GetString("TooltipContBatching");
    public string TooltipTimeout => GetString("TooltipTimeout");
    public string TooltipCachePrompt => GetString("TooltipCachePrompt");
    public string TooltipMlock => GetString("TooltipMlock");
    public string TooltipMmap => GetString("TooltipMmap");
    public string TooltipReasoning => GetString("TooltipReasoning");
    public string TooltipReasoningBudget => GetString("TooltipReasoningBudget");
    public string TooltipSeed => GetString("TooltipSeed");
    public string TooltipPresencePenalty => GetString("TooltipPresencePenalty");
    public string TooltipFrequencyPenalty => GetString("TooltipFrequencyPenalty");
    public string TooltipContextShift => GetString("TooltipContextShift");

    public string PlaceholderParallelSlots => GetString("PlaceholderParallelSlots");
    public string PlaceholderTimeout => GetString("PlaceholderTimeout");
    public string PlaceholderReasoningBudget => GetString("PlaceholderReasoningBudget");
    public string PlaceholderSeed => GetString("PlaceholderSeed");
    public string PlaceholderPresencePenalty => GetString("PlaceholderPresencePenalty");
    public string PlaceholderFrequencyPenalty => GetString("PlaceholderFrequencyPenalty");

    public string TabSpeculative => GetString("TabSpeculative");
    public string SpeculativeDecoding => GetString("SpeculativeDecoding");
    public string SpecType => GetString("SpecType");
    public string TooltipSpecType => GetString("TooltipSpecType");
    public string SpecGeneralParams => GetString("SpecGeneralParams");
    public string SpecDraftNMax => GetString("SpecDraftNMax");
    public string SpecDraftNMin => GetString("SpecDraftNMin");
    public string SpecDraftPSplit => GetString("SpecDraftPSplit");
    public string SpecDraftPMin => GetString("SpecDraftPMin");
    public string TooltipSpecDraftNMax => GetString("TooltipSpecDraftNMax");
    public string TooltipSpecDraftNMin => GetString("TooltipSpecDraftNMin");
    public string TooltipSpecDraftPSplit => GetString("TooltipSpecDraftPSplit");
    public string TooltipSpecDraftPMin => GetString("TooltipSpecDraftPMin");
    public string PlaceholderSpecDraftNMax => GetString("PlaceholderSpecDraftNMax");
    public string PlaceholderSpecDraftNMin => GetString("PlaceholderSpecDraftNMin");
    public string PlaceholderSpecDraftPSplit => GetString("PlaceholderSpecDraftPSplit");
    public string PlaceholderSpecDraftPMin => GetString("PlaceholderSpecDraftPMin");
    public string DraftModelParams => GetString("DraftModelParams");
    public string SpecDraftModel => GetString("SpecDraftModel");
    public string TooltipSpecDraftModel => GetString("TooltipSpecDraftModel");
    public string PlaceholderSpecDraftModel => GetString("PlaceholderSpecDraftModel");
    public string SpecDraftGpuLayers => GetString("SpecDraftGpuLayers");
    public string TooltipSpecDraftGpuLayers => GetString("TooltipSpecDraftGpuLayers");
    public string PlaceholderSpecDraftGpuLayers => GetString("PlaceholderSpecDraftGpuLayers");

    public string FeatureNotSupported => GetString("FeatureNotSupported");
    public string UnsupportedArgWarning => GetString("UnsupportedArgWarning");

    public string HuggingFace => GetString("HuggingFace");
    public string HfRepo => GetString("HfRepo");
    public string HfFile => GetString("HfFile");
    public string Offline => GetString("Offline");
    public string HfRepoDraft => GetString("HfRepoDraft");
    public string PlaceholderHfRepo => GetString("PlaceholderHfRepo");
    public string PlaceholderHfFile => GetString("PlaceholderHfFile");
    public string PlaceholderHfRepoDraft => GetString("PlaceholderHfRepoDraft");
    public string TooltipHfRepo => GetString("TooltipHfRepo");
    public string TooltipHfFile => GetString("TooltipHfFile");
    public string TooltipOffline => GetString("TooltipOffline");
    public string TooltipHfRepoDraft => GetString("TooltipHfRepoDraft");

    public string AboutTitle => GetString("AboutTitle");
    public string AboutVersion => GetString("AboutVersion");
    public string AboutUpdateAvailable => GetString("AboutUpdateAvailable");
    public string MarkdownViewerTitle => GetString("MarkdownViewerTitle");
    public string Developer => GetString("Developer");
    public string AppRepository => GetString("AppRepository");
    public string TooltipAbout => GetString("TooltipAbout");
    public string ThanksMethelina => GetString("ThanksMethelina");
    public string OptimizationAttribution => GetString("OptimizationAttribution");

    public string UseDefaultDataPath => GetString("UseDefaultDataPath");
    public string DataPathTooltipDefault => GetString("DataPathTooltipDefault");
    public string DataPathTooltipCustom => GetString("DataPathTooltipCustom");
    public string ConfirmMoveToDefault => GetString("ConfirmMoveToDefault");
    public string ConfirmMoveToCustom => GetString("ConfirmMoveToCustom");
    public string MigrationSuccess => GetString("MigrationSuccess");
    public string MigrationError => GetString("MigrationError");
    public string SelectDataDirectory => GetString("SelectDataDirectory");
    public string SuccessTitle => GetString("SuccessTitle");

    public string DropExeConfirmTitle => GetString("DropExeConfirmTitle");
    public string DropExeConfirmMessage => GetString("DropExeConfirmMessage");
    public string DropExeSet => GetString("DropExeSet");
    public string DropModelSet => GetString("DropModelSet");
    public string DropMmprojSet => GetString("DropMmprojSet");
    public string DropExeSetLog => GetString("DropExeSetLog");
    public string DropOverlaySupported => GetString("DropOverlaySupported");

    public string UpdateApp => GetString("UpdateApp");
    public string AppUpdateAvailable => GetString("AppUpdateAvailable");
    public string AppUpdateDownloading => GetString("AppUpdateDownloading");
    public string AppUpdateRestarting => GetString("AppUpdateRestarting");
    public string AppUpdateFailed => GetString("AppUpdateFailed");
    public string AppUpdateConfirm => GetString("AppUpdateConfirm");
    public string PickArguments => GetString("PickArguments");
    public string TooltipPickArguments => GetString("TooltipPickArguments");
    public string ArgumentPickerTitle => GetString("ArgumentPickerTitle");
    public string ArgumentPickerFilter => GetString("ArgumentPickerFilter");
    public string ArgumentPickerFlag => GetString("ArgumentPickerFlag");
    public string ArgumentPickerDescription => GetString("ArgumentPickerDescription");
    public string ArgumentPickerDefault => GetString("ArgumentPickerDefault");
    public string ArgumentPickerAdd => GetString("ArgumentPickerAdd");
    public string ArgumentPickerCancel => GetString("ArgumentPickerCancel");
    public string NoHelpAvailable => GetString("NoHelpAvailable");

    public string TabDocker => GetString("TabDocker");
    public string DockerSettings => GetString("DockerSettings");
    public string RunInDocker => GetString("RunInDocker");
    public string DockerRemoveOnStop => GetString("DockerRemoveOnStop");
    public string DockerUseAllGpus => GetString("DockerUseAllGpus");
    public string DockerImage => GetString("DockerImage");
    public string DockerContainerName => GetString("DockerContainerName");
    public string DockerNotInstalled => GetString("DockerNotInstalled");
    public string DockerNotInstalledError => GetString("DockerNotInstalledError");
    public string PlaceholderDockerContainerName => GetString("PlaceholderDockerContainerName");
    public string TooltipRunInDocker => GetString("TooltipRunInDocker");
    public string TooltipDockerRemoveOnStop => GetString("TooltipDockerRemoveOnStop");
    public string TooltipDockerUseAllGpus => GetString("TooltipDockerUseAllGpus");
    public string TooltipDockerImage => GetString("TooltipDockerImage");
    public string TooltipDockerContainerName => GetString("TooltipDockerContainerName");

    public string ModelLoadModeStatusRouting => GetString("ModelLoadModeStatusRouting");
    public string ModelLoadModeStatusSingleModel => GetString("ModelLoadModeStatusSingleModel");
    public string ModelLoadModeStatusHfRepo => GetString("ModelLoadModeStatusHfRepo");
    public string ModelLoadModeConflictToast => GetString("ModelLoadModeConflictToast");
    public string ModelLoadModeConflictHfToast => GetString("ModelLoadModeConflictHfToast");

    public string UpdateCheckIntervals => GetString("UpdateCheckIntervals");
    public string AppUpdateCheckInterval => GetString("AppUpdateCheckInterval");
    public string LlamaUpdateCheckInterval => GetString("LlamaUpdateCheckInterval");
    public string TooltipAppUpdateCheckInterval => GetString("TooltipAppUpdateCheckInterval");
    public string TooltipLlamaUpdateCheckInterval => GetString("TooltipLlamaUpdateCheckInterval");
    public string UpdateIntervalWarning => GetString("UpdateIntervalWarning");

    public string ConfirmStopInstance => GetString("ConfirmStopInstance");
    public string PortCollisionToast => GetString("PortCollisionToast");
    public string ConfirmStopServer => GetString("ConfirmStopServer");
    public string TooltipConfirmStopServer => GetString("TooltipConfirmStopServer");
    public string Behavior => GetString("Behavior");
    public string TooltipInstanceSplitButton => GetString("TooltipInstanceSplitButton");
    public string ServerStartFailedToast => GetString("ServerStartFailedToast");
    public string ToastSavedExecutableNotFound => GetString("ToastSavedExecutableNotFound");
    public string ToastClickToApply => GetString("ToastClickToApply");

    public string LogStreaming => GetString("LogStreaming");
    public string LogStreamingEnabled => GetString("LogStreamingEnabled");
    public string LogStreamingPort => GetString("LogStreamingPort");
    public string LogStreamingToken => GetString("LogStreamingToken");
    public string LogStreamingTokenHint => GetString("LogStreamingTokenHint");
    public string LogStreamingRestart => GetString("LogStreamingRestart");
    public string LogStreamingRunning => GetString("LogStreamingRunning");
    public string LogStreamingStopped => GetString("LogStreamingStopped");
    public string LogStreamingClients => GetString("LogStreamingClients");
    public string TooltipLogStreamingEnabled => GetString("TooltipLogStreamingEnabled");
    public string TooltipLogStreamingPort => GetString("TooltipLogStreamingPort");
    public string TooltipLogStreamingToken => GetString("TooltipLogStreamingToken");
    public string TooltipLogStreamingTokenHint => GetString("TooltipLogStreamingTokenHint");
    public string TooltipLogStreamingRestart => GetString("TooltipLogStreamingRestart");

    public string OnDemandProxy => GetString("OnDemandProxy");
    public string OnDemandProxyEnabledLabel => GetString("OnDemandProxyEnabledLabel");
    public string OnDemandProxyHint => GetString("OnDemandProxyHint");
    public string OnDemandProxyPortLabel => GetString("OnDemandProxyPortLabel");
    public string OnDemandProxyRestart => GetString("OnDemandProxyRestart");
    public string OnDemandProxyIdle => GetString("OnDemandProxyIdle");
    public string OnDemandProxyHealthTimeout => GetString("OnDemandProxyHealthTimeout");
    public string OnDemandProxyApiKeyLabel => GetString("OnDemandProxyApiKeyLabel");
    public string ComfyUiSection => GetString("ComfyUiSection");
    public string ComfyUiFreeEnabledLabel => GetString("ComfyUiFreeEnabledLabel");
    public string ComfyUiUrlLabel => GetString("ComfyUiUrlLabel");
    public string TooltipOnDemandProxyEnabled => GetString("TooltipOnDemandProxyEnabled");
    public string TooltipOnDemandProxyPort => GetString("TooltipOnDemandProxyPort");
    public string TooltipOnDemandProxyIdle => GetString("TooltipOnDemandProxyIdle");
    public string TooltipOnDemandProxyHealthTimeout => GetString("TooltipOnDemandProxyHealthTimeout");
    public string TooltipOnDemandProxyApiKey => GetString("TooltipOnDemandProxyApiKey");
    public string TooltipComfyUiFreeEnabled => GetString("TooltipComfyUiFreeEnabled");
    public string TooltipComfyUiUrl => GetString("TooltipComfyUiUrl");

    public string ScenariosEnabled => GetString("ScenariosEnabled");
    public string Scenario => GetString("Scenario");
    public string RunScenario => GetString("RunScenario");
    public string EditScenario => GetString("EditScenario");
    public string CreateScenario => GetString("CreateScenario");
    public string DeleteScenario => GetString("DeleteScenario");
    public string AutoStartScenario => GetString("AutoStartScenario");
    public string ScenarioName => GetString("ScenarioName");
    public string ScenarioInterval => GetString("ScenarioInterval");
    public string ScenarioProfiles => GetString("ScenarioProfiles");
    public string ScenarioAutoStart => GetString("ScenarioAutoStart");
    public string ConfirmDeleteScenario => GetString("ConfirmDeleteScenario");
    public string ScenarioNoProfiles => GetString("ScenarioNoProfiles");
    public string ScenarioNameRequired => GetString("ScenarioNameRequired");
    public string ScenarioDialogTitleCreate => GetString("ScenarioDialogTitleCreate");
    public string ScenarioDialogTitleEdit => GetString("ScenarioDialogTitleEdit");
    public string ScenarioRunning => GetString("ScenarioRunning");
    public string ScenarioCompleted => GetString("ScenarioCompleted");
    public string ScenarioAutoStarted => GetString("ScenarioAutoStarted");
    public string ScenarioProfileNotFound => GetString("ScenarioProfileNotFound");
    public string TooltipScenarioSplitButton => GetString("TooltipScenarioSplitButton");
    public string ScenarioAvailableProfiles => GetString("ScenarioAvailableProfiles");
    public string ScenarioSelectedProfiles => GetString("ScenarioSelectedProfiles");
    public string ScenarioNameExists => GetString("ScenarioNameExists");
    public string AutoStartWithSystem => GetString("AutoStartWithSystem");
    public string TooltipAutoStartWithSystem => GetString("TooltipAutoStartWithSystem");
    public string DataStorage => GetString("DataStorage");

    public string Clone => GetString("Clone");
    public string CloneProfileTitle => GetString("CloneProfileTitle");
    public string CloneProfileNameLabel => GetString("CloneProfileNameLabel");
    public string CloneProfileNameExists => GetString("CloneProfileNameExists");
    public string CloneProfileNameEmpty => GetString("CloneProfileNameEmpty");
    public string CloneProfileHost => GetString("CloneProfileHost");
    public string CloneProfilePort => GetString("CloneProfilePort");
    public string CloneProfileContextSize => GetString("CloneProfileContextSize");
    public string CloneToScenario => GetString("CloneToScenario");
    public string CustomBrowserPath => GetString("CustomBrowserPath");
    public string TooltipCustomBrowserPath => GetString("TooltipCustomBrowserPath");
    public string SelectInstalledBrowser => GetString("SelectInstalledBrowser");
    public string ConfirmStopForUpdate => GetString("ConfirmStopForUpdate");
    public string ToastAutoFitHeightDisabled => GetString("ToastAutoFitHeightDisabled");

    public string ExperimentalRepos => GetString("ExperimentalRepos");
    public string Add => GetString("Add");
    public string Edit => GetString("Edit");
    public string ExperimentalReposEnabled => GetString("ExperimentalReposEnabled");
    public string ExperimentalUpdateInterval => GetString("ExperimentalUpdateInterval");
    public string ExperimentalRepoList => GetString("ExperimentalRepoList");
    public string AddDefaultRepos => GetString("AddDefaultRepos");
    public string RepoUrl => GetString("RepoUrl");
    public string DisplayName => GetString("DisplayName");
    public string FilterTags => GetString("FilterTags");
    public string ExperimentalRepoDialogTitle => GetString("ExperimentalRepoDialogTitle");
    public string ExperimentalRepoEditTitle => GetString("ExperimentalRepoEditTitle");
    public string RepoUrlInvalid => GetString("RepoUrlInvalid");
    public string OfficialTab => GetString("OfficialTab");
    public string ExperimentalTab => GetString("ExperimentalTab");
    public string ExperimentalRepoSelect => GetString("ExperimentalRepoSelect");
    public string ExperimentalUpdateToast => GetString("ExperimentalUpdateToast");

    // Optimization (HPO) window
    public string OptTitle => GetString("OptTitle");
    public string OptGuideTitle => GetString("OptGuideTitle");
    public string OptGuideTooltip => GetString("OptGuideTooltip");
    public string OptOpen => GetString("OptOpen");
    public string OptSettings => GetString("OptSettings");
    public string OptLlamaBenchPath => GetString("OptLlamaBenchPath");
    public string OptMetric => GetString("OptMetric");
    public string OptMetricTg => GetString("OptMetricTg");
    public string OptMetricPp => GetString("OptMetricPp");
    public string OptMetricMean => GetString("OptMetricMean");
    public string OptOverrideMode => GetString("OptOverrideMode");
    public string OptOverrideModeNone => GetString("OptOverrideModeNone");
    public string OptOverrideModeScan => GetString("OptOverrideModeScan");
    public string OptTrials => GetString("OptTrials");
    public string OptRepeat => GetString("OptRepeat");
    public string OptNTokens => GetString("OptNTokens");
    public string OptWarmupRuns => GetString("OptWarmupRuns");
    public string OptNglMax => GetString("OptNglMax");
    public string OptRanges => GetString("OptRanges");
    public string OptLow => GetString("OptLow");
    public string OptHigh => GetString("OptHigh");
    public string OptNoWarmup => GetString("OptNoWarmup");
    public string OptUseFit => GetString("OptUseFit");
    public string OptUseFitHint => GetString("OptUseFitHint");
    public string OptFitMargin => GetString("OptFitMargin");
    public string OptEstimateContext => GetString("OptEstimateContext");
    public string OptPruneBatchLtUbatch => GetString("OptPruneBatchLtUbatch");
    public string OptUseHttpBenchmark => GetString("OptUseHttpBenchmark");
    public string OptNoMmap => GetString("OptNoMmap");
    public string OptNoImprovementApply => GetString("OptNoImprovementApply");
    public string OptBenchPathPlaceholder => GetString("OptBenchPathPlaceholder");
    public string OptNglMaxPlaceholder => GetString("OptNglMaxPlaceholder");
    public string OptCtxPlaceholder => GetString("OptCtxPlaceholder");
    public string OptProgEstimatingNgl => GetString("OptProgEstimatingNgl");
    public string OptProgProbingNgl => GetString("OptProgProbingNgl");
    public string OptProgWarmup => GetString("OptProgWarmup");
    public string OptProgWarmupResult => GetString("OptProgWarmupResult");
    public string OptProgComparison => GetString("OptProgComparison");
    public string OptProgEstimatingCtx => GetString("OptProgEstimatingCtx");
    public string OptProgProbingCtx => GetString("OptProgProbingCtx");
    public string OptProgBenchmarking => GetString("OptProgBenchmarking");
    public string OptWarnFitNoCtx => GetString("OptWarnFitNoCtx");
    public string OptWarnNoFitFlag => GetString("OptWarnNoFitFlag");
    public string OptWarnNoCtxFlag => GetString("OptWarnNoCtxFlag");
    public string OptWarnNoCacheFlag => GetString("OptWarnNoCacheFlag");
    public string OptErrServerNotFound => GetString("OptErrServerNotFound");
    public string OptErrBenchNotFound => GetString("OptErrBenchNotFound");
    public string OptTuneNCpuMoe => GetString("OptTuneNCpuMoe");
    public string OptTuneNCpuMoeHint => GetString("OptTuneNCpuMoeHint");
    public string OptCpuMoe => GetString("OptCpuMoe");
    public string OptRun => GetString("OptRun");
    public string OptStop => GetString("OptStop");
    public string OptColStage => GetString("OptColStage");
    public string OptColTokensPerSec => GetString("OptColTokensPerSec");
    public string OptColCommand => GetString("OptColCommand");
    public string OptResult => GetString("OptResult");
    public string OptImprovement => GetString("OptImprovement");
    public string OptRecommendedCtx => GetString("OptRecommendedCtx");
    public string OptServerCommand => GetString("OptServerCommand");
    public string OptApplyToConfig => GetString("OptApplyToConfig");
    public string OptApplied => GetString("OptApplied");
    public string OptDone => GetString("OptDone");
    public string OptStopped => GetString("OptStopped");
    public string OptError => GetString("OptError");
    public string OptErrorNoModel => GetString("OptErrorNoModel");
    public string OptStageProgressFormat => GetString("OptStageProgressFormat");
    public string OptRuntime => GetString("OptRuntime");
    public string OptRuntimeHint => GetString("OptRuntimeHint");
    public string OptCacheTypeK => GetString("OptCacheTypeK");
    public string OptCacheTypeV => GetString("OptCacheTypeV");
    public string OptMmproj => GetString("OptMmproj");
}